# Generated by Django 3.1.2 on 2020-10-29 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_similarity'),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchTrain',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('action', models.CharField(db_column='action', max_length=255)),
                ('input', models.CharField(db_column='input', max_length=255)),
            ],
            options={
                'db_table': 'search_train',
                'managed': False,
            },
        ),
    ]
